name: Android Build

on:
  push:
    branches: [ "main" ]

env:
  BUILD_NUMBER: ${{ github.run_number }}
  VERSION_NAME: 1.0.${{ github.run_number }}


jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Gradle Build Action
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-overwrite-existing: true

      - name: Set Environment Variables
        run: |
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
          echo "VERSION_NAME=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew assemble


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.BUILD_NUMBER }}
          name: Release v${{ env.BUILD_NUMBER }}
          body: "Automated release for build ${{ env.BUILD_NUMBER }}"
          draft: false
          prerelease: false
          files: app/build/outputs/apk/release/app-release.apk
